"""phase 6: self appraisals and transfers

Revision ID: b44c6a117db9
Revises: 0bd3259e2bd4
Create Date: 2026-07-20 01:31:52.596010

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44c6a117db9'
down_revision: str | None = '0bd3259e2bd4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('from_department_id', sa.BigInteger(), nullable=False),
    sa.Column('to_department_id', sa.BigInteger(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_department_id <> to_department_id', name=op.f('ck_transfer_requests_different_departments')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_transfer_requests_employee_id')),
    sa.ForeignKeyConstraint(['from_department_id'], ['departments.id'], name=op.f('fk_transfer_requests_from_department_id')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_transfer_requests_requested_by_user_id')),
    sa.ForeignKeyConstraint(['to_department_id'], ['departments.id'], name=op.f('fk_transfer_requests_to_department_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_requests'))
    )
    op.create_index(op.f('ix_transfer_requests_employee_id'), 'transfer_requests', ['employee_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_employee_salaries_employee_id and
    # ix_position_rates_position_id — the same pre-existing Phase 2 index/ORM drift
    # noted in every migration since Phase 3. Deliberately not touched here either.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_requests_employee_id'), table_name='transfer_requests')
    op.drop_table('transfer_requests')
    # ### end Alembic commands ###
