"""phase 7: incentive runs and calculation engine

Revision ID: d7c84014bc07
Revises: b44c6a117db9
Create Date: 2026-07-20 03:01:04.989176

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7c84014bc07'
down_revision: str | None = 'b44c6a117db9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incentive_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('run_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exceptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_incentive_runs_created_by_user_id')),
    sa.ForeignKeyConstraint(['period_id'], ['incentive_periods.id'], name=op.f('fk_incentive_runs_period_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incentive_runs')),
    sa.UniqueConstraint('period_id', 'run_no', name='uq_incentive_runs_period_run_no')
    )
    op.create_index(op.f('ix_incentive_runs_period_id'), 'incentive_runs', ['period_id'], unique=False)
    op.create_index('uq_incentive_runs_one_approved_per_period', 'incentive_runs', ['period_id'], unique=True, postgresql_where=sa.text("status = 'approved'"))
    op.create_table('incentive_line_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('evaluation_id', sa.BigInteger(), nullable=True),
    sa.Column('evaluation_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('formula_mode', sa.String(length=20), nullable=False),
    sa.Column('flat_ref_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('position_incentive_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('attendance_factor', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('target_ratio', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('computed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('override_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('exclude_reason', sa.Text(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_incentive_line_items_employee_id')),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_incentive_line_items_evaluation_id')),
    sa.ForeignKeyConstraint(['run_id'], ['incentive_runs.id'], name=op.f('fk_incentive_line_items_run_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incentive_line_items')),
    sa.UniqueConstraint('run_id', 'employee_id', name='uq_incentive_line_items_run_employee')
    )
    op.create_index(op.f('ix_incentive_line_items_employee_id'), 'incentive_line_items', ['employee_id'], unique=False)
    op.create_index(op.f('ix_incentive_line_items_run_id'), 'incentive_line_items', ['run_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_employee_salaries_employee_id and
    # ix_position_rates_position_id — the same pre-existing Phase 2 index/ORM drift
    # noted in every migration since Phase 3. Deliberately not touched here either.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incentive_line_items_run_id'), table_name='incentive_line_items')
    op.drop_index(op.f('ix_incentive_line_items_employee_id'), table_name='incentive_line_items')
    op.drop_table('incentive_line_items')
    op.drop_index('uq_incentive_runs_one_approved_per_period', table_name='incentive_runs', postgresql_where=sa.text("status = 'approved'"))
    op.drop_index(op.f('ix_incentive_runs_period_id'), table_name='incentive_runs')
    op.drop_table('incentive_runs')
    # ### end Alembic commands ###
